// Generated by delegate_gen on Sat Aug 10 14:39:58 PDT 2013
package info.bytecraft.api;

public abstract class OfflineDelegate
{
    private org.bukkit.OfflinePlayer delegate;

    protected OfflineDelegate(org.bukkit.OfflinePlayer d)
    {
        this.delegate = d;
    }

    public void setDelegate(org.bukkit.OfflinePlayer v)
    {
        this.delegate = v;
    }

    public org.bukkit.OfflinePlayer getDelegate()
    {
        return delegate;
    }

    private void checkState()
    {
        if (delegate == null) {
            throw new IllegalStateException(
                "Can't be used when delegate isn't set.");
        }
    }

    public java.lang.String getName()
    {
        checkState();
        return delegate.getName();
    }

    public boolean isOnline()
    {
        checkState();
        return delegate.isOnline();
    }

    public boolean isBanned()
    {
        checkState();
        return delegate.isBanned();
    }

    public void setBanned(boolean p0)
    {
        checkState();
        delegate.setBanned(p0);
    }

    public org.bukkit.entity.Player getPlayer()
    {
        checkState();
        return delegate.getPlayer();
    }

    public org.bukkit.Location getBedSpawnLocation()
    {
        checkState();
        return delegate.getBedSpawnLocation();
    }

    public boolean isWhitelisted()
    {
        checkState();
        return delegate.isWhitelisted();
    }

    public void setWhitelisted(boolean p0)
    {
        checkState();
        delegate.setWhitelisted(p0);
    }

    public long getFirstPlayed()
    {
        checkState();
        return delegate.getFirstPlayed();
    }

    public long getLastPlayed()
    {
        checkState();
        return delegate.getLastPlayed();
    }

    public boolean hasPlayedBefore()
    {
        checkState();
        return delegate.hasPlayedBefore();
    }

    public boolean isOp()
    {
        checkState();
        return delegate.isOp();
    }

    public void setOp(boolean p0)
    {
        checkState();
        delegate.setOp(p0);
    }

    public java.util.Map<java.lang.String, java.lang.Object> serialize()
    {
        checkState();
        return delegate.serialize();
    }

}
