name: Bytecraft
author: Sabersamus
main: info.bytecraft.Bytecraft
description: The plugin for Bytecraft
version: 0.0.1
commands:
    ban:
        description: Ban a player
        usage: /<command> <player>
    bless:
        description: Bless a block for a player
        usage: /<command> <player>
    channel:
        description: Change your chat channel
        usage: /<command> <channel>
    creative:
        description: Change your gamemode to creative
        usage: /<command>
    fill:
        description: Fill some blocks
        usage: /<command> <material>
    gamemode:
        description: Change your gamemode
        usage: /<command> [creative|survival]
        aliases: [gm]
    give:
        description: Give another player an item
        usage: /<command> <player> <id|name> <amount> <data>
    god:
        description: Send a message as the default red god
        usage: /<command> <message>
    item:
        description: Give yourself an item
        usage: /<command> <id|name> <amount> <data>
        aliases: [i]
    kick:
        description: Kick a player
        usage: /<command> <player>
    kill:
        description: Kill yourself
        usage: /<command>
    message:
        description: Send a message to another player
        usage: /<command> <player> <message>
        aliases: [m, to]
    say:
        description: Send a message as god
        usage: /<command> <message>
    summon:
        description: Summon a player to your location
        usage: /<command> <player>
        aliases: [s, tphere]
    survival:
        description: Change your gamemode to survival
        usage: /<command>
    time:
        description: Change your personal time
        usage: /<command> [day|night|normal]
    tpblock:
        description: Manage your teleport block
        usage: /<command> <on|off|status>
    teleport:
        description: Teleport to a player
        usage: /<command> <player>
        aliases: [tp, tele]
    user:
        description: Manage players permissions
        usage: /<command> make <setter|warned|hardwarned> <player>
    vanish:
        description: Vanish
        usage: /<command>
        aliases: [v]
    wallet:
        description: Manage your wallet
        usage: /<command> <balance>
    warp:
        description: Warp to a far away land
        usage: /<command> city
    who:
        description: See who's online
        usage: /<command>
        aliases: [list]